from datetime import datetime
from pathlib import Path


class ReadmeGenerator:
    def generate(self, session, output="README_GENERATED.md"):
        path = Path(output)
        best = session.best_result or {}
        text = f"""# ARM Developer AutoPilot

AI model optimization for ARM CPU deployment.

Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}

## Project

- **Project:** {session.project_name}
- **Language:** {session.language}
- **Models detected:** {len(session.models or [])}

## Best Optimization

| Metric | Result |
|---|---|
| Quantization | {best.get('quantization', '-')} |
| Threads | {best.get('threads', '-')} |
| Graph Optimization | {best.get('graph_optimization', '-')} |
| Execution Mode | {best.get('execution_mode', '-')} |
| Latency | {best.get('latency', '-')} ms |
| Memory | {best.get('memory', '-')} MB |
| Model Size | {best.get('model_size', '-')} MB |
| Score | {best.get('score', '-')} |

## Features

- Project and AI model detection
- FP32 / INT8 optimization
- ARM CPU thread tuning
- ONNX Runtime benchmarking
- Optimization candidate search and ranking
- Streamlit dashboard
- HTML and PDF reports
- GitHub project publishing

## Reports

Generated reports are available in the `reports/` directory.

---

Generated by **ARM Developer AutoPilot**.
"""
        path.write_text(text, encoding="utf-8")
        return str(path)
