from pathlib import Path
from datetime import datetime
import html


class ReportGenerator:
    """
    Generates HTML and PDF optimization reports.
    """

    def __init__(self, output_dir="reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _get_value(self, data, key, default="-"):
        if data is None:
            return default

        if isinstance(data, dict):
            return data.get(key, default)

        return getattr(data, key, default)

    def _build_html(self, session):
        best = getattr(session, "best_result", None)

        if best is None and isinstance(session, dict):
            best = session.get("best_result", session)

        project_name = self._get_value(
            session,
            "project_name",
            "ARM Optimization Project"
        )

        language = self._get_value(
            session,
            "language",
            "-"
        )

        quantization = self._get_value(
            best,
            "quantization",
            "-"
        )

        threads = self._get_value(
            best,
            "threads",
            "-"
        )

        latency = self._get_value(
            best,
            "latency",
            "-"
        )

        memory = self._get_value(
            best,
            "memory",
            "-"
        )

        model_size = self._get_value(
            best,
            "model_size",
            "-"
        )

        score = self._get_value(
            best,
            "score",
            "-"
        )

        graph_optimization = self._get_value(
            best,
            "graph_optimization",
            "-"
        )

        execution_mode = self._get_value(
            best,
            "execution_mode",
            "-"
        )

        generated = datetime.now().strftime(
            "%d-%m-%Y %H:%M:%S"
        )

        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">

<title>ARM Developer AutoPilot Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 40px;
    background: #f5f7fa;
    color: #222;
}}

.container {{
    max-width: 1000px;
    margin: auto;
    background: white;
    padding: 40px;
    border-radius: 12px;
}}

h1 {{
    margin-bottom: 5px;
}}

.subtitle {{
    color: #666;
    margin-bottom: 30px;
}}

h2 {{
    margin-top: 35px;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    margin-top: 15px;
}}

th, td {{
    padding: 12px;
    border-bottom: 1px solid #ddd;
    text-align: left;
}}

th {{
    background: #f0f2f5;
}}

.highlight {{
    font-size: 22px;
    font-weight: bold;
}}

.footer {{
    margin-top: 40px;
    color: #777;
    font-size: 13px;
}}

</style>

</head>

<body>

<div class="container">

<h1>ARM Developer AutoPilot</h1>

<div class="subtitle">
Automated ARM AI Optimization Report
</div>

<h2>Project Information</h2>

<table>

<tr>
<th>Project</th>
<td>{html.escape(str(project_name))}</td>
</tr>

<tr>
<th>Language</th>
<td>{html.escape(str(language))}</td>
</tr>

<tr>
<th>Generated</th>
<td>{generated}</td>
</tr>

</table>


<h2>Best Configuration</h2>

<table>

<tr>
<th>Optimization</th>
<th>Value</th>
</tr>

<tr>
<td>Quantization</td>
<td>{html.escape(str(quantization))}</td>
</tr>

<tr>
<td>CPU Threads</td>
<td>{html.escape(str(threads))}</td>
</tr>

<tr>
<td>Graph Optimization</td>
<td>{html.escape(str(graph_optimization))}</td>
</tr>

<tr>
<td>Execution Mode</td>
<td>{html.escape(str(execution_mode))}</td>
</tr>

<tr>
<td>Latency</td>
<td>{html.escape(str(latency))} ms</td>
</tr>

<tr>
<td>Memory</td>
<td>{html.escape(str(memory))} MB</td>
</tr>

<tr>
<td>Model Size</td>
<td>{html.escape(str(model_size))} MB</td>
</tr>

<tr>
<td>Score</td>
<td class="highlight">{html.escape(str(score))}</td>
</tr>

</table>


<h2>Optimization Workflow</h2>

<p>
ARM Developer AutoPilot automatically analyzes the project,
detects AI models, generates optimization candidates,
benchmarks configurations, ranks their performance,
and recommends the best configuration.
</p>

<p>
The optimization workflow includes FP32/INT8 quantization,
CPU thread tuning, graph optimization, runtime configuration,
benchmarking, and candidate ranking.
</p>


<h2>Optimization Pipeline</h2>

<p>
<strong>
Analyze → Optimize → Benchmark → Recommend → Report → Deploy
</strong>
</p>


<div class="footer">

Generated by ARM Developer AutoPilot.

</div>

</div>

</body>
</html>
"""

    def generate_html(self, session):
        path = self.output_dir / "optimization_report.html"

        content = self._build_html(session)

        path.write_text(
            content,
            encoding="utf-8"
        )

        return str(path)

    def generate_pdf(self, session):
        path = self.output_dir / "optimization_report.pdf"

        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.platypus import (
                SimpleDocTemplate,
                Paragraph,
                Spacer,
                Table,
                TableStyle
            )
            from reportlab.lib import colors
            from reportlab.lib.styles import getSampleStyleSheet

        except ImportError:
            raise RuntimeError(
                "reportlab is required for PDF generation. "
                "Add reportlab to requirements.txt."
            )

        best = getattr(session, "best_result", None)

        if best is None and isinstance(session, dict):
            best = session.get("best_result", session)

        project_name = self._get_value(
            session,
            "project_name",
            "ARM Optimization Project"
        )

        language = self._get_value(
            session,
            "language",
            "-"
        )

        styles = getSampleStyleSheet()

        document = SimpleDocTemplate(
            str(path),
            pagesize=A4
        )

        elements = []

        elements.append(
            Paragraph(
                "ARM Developer AutoPilot",
                styles["Title"]
            )
        )

        elements.append(
            Paragraph(
                "Automated ARM AI Optimization Report",
                styles["Heading2"]
            )
        )

        elements.append(Spacer(1, 20))

        elements.append(
            Paragraph(
                f"Project: {project_name}",
                styles["Normal"]
            )
        )

        elements.append(
            Paragraph(
                f"Language: {language}",
                styles["Normal"]
            )
        )

        elements.append(Spacer(1, 20))

        data = [
            ["Metric", "Value"],
            [
                "Quantization",
                str(self._get_value(best, "quantization"))
            ],
            [
                "CPU Threads",
                str(self._get_value(best, "threads"))
            ],
            [
                "Graph Optimization",
                str(self._get_value(best, "graph_optimization"))
            ],
            [
                "Execution Mode",
                str(self._get_value(best, "execution_mode"))
            ],
            [
                "Latency",
                f"{self._get_value(best, 'latency')} ms"
            ],
            [
                "Memory",
                f"{self._get_value(best, 'memory')} MB"
            ],
            [
                "Model Size",
                f"{self._get_value(best, 'model_size')} MB"
            ],
            [
                "Score",
                str(self._get_value(best, "score"))
            ]
        ]

        table = Table(data, colWidths=[220, 220])

        table.setStyle(
            TableStyle([
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.lightgrey
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey
                ),
                (
                    "PADDING",
                    (0, 0),
                    (-1, -1),
                    8
                )
            ])
        )

        elements.append(table)

        elements.append(Spacer(1, 25))

        elements.append(
            Paragraph(
                "Optimization Workflow",
                styles["Heading2"]
            )
        )

        elements.append(
            Paragraph(
                "Analyze → Optimize → Benchmark → "
                "Recommend → Report → Deploy",
                styles["Normal"]
            )
        )

        document.build(elements)

        return str(path)

    def generate(self, session):
        """
        Generate both HTML and PDF reports.
        """

        html_path = self.generate_html(session)
        pdf_path = self.generate_pdf(session)

        return {
            "html": html_path,
            "pdf": pdf_path
        }